Update csv2libsvm.py
_csv.Error: iterator should return strings, not bytes error was coming in python 3 since the file was opened in binary mode.
Hence removing the binary mode.